### ISSUE TITLE
Incompatible with prometheus-client 1.x

### ISSUE THREAD

**Issue by mdub** [harmjanblok/puma-metrics#16]
I'm trying to use `puma-metrics` in an app where I'm already using `prometheus-client 1.0.0`, but it's currently not possible, due to the dependency:

```
spec.add_runtime_dependency 'prometheus-client', '~> 0.10'
```

Can that dependency be relaxed?

**Comment by harmjanblok** [comment]
Has been relaxed and release in version `1.2.0`.
