### ISSUE TITLE
Support Puma 5

### ISSUE THREAD

**Issue by avlazarov** [harmjanblok/puma-metrics#22]
Puma 5 is our and a few changes are made relevant to this gem:

* The default threads on MRI are now 5 not 16 hence a few tests depending on this default will fail ([example](https://github.com/harmjanblok/puma-metrics/blob/83a0590c90c4e31e558d42b92cd7a3608a1ae9a0/test/test_cluster_more.rb#L37)). Should be better to configure the values explicitly so the tests are not coupled to the Puma version.
* There is a new per worker server stat `requests_count` that would be nice to expose as a Prometheus metric.

**Comment by harmjanblok** [comment]
@avlazarov thanks for your input, I've just released version 1.2.2 which includes the new `requests_count` metric when using Puma 5. Older puma versions only show this metric could be present, but don't include any value for request count.

Also I've update the test as you suggested and predefined the expected threads.
